id: AB892CC9C
title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
type: translation
pechas:
- I6EB4C046
- IA690F999
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:09:59.691701
  last_modified_at: 2023-01-04 13:09:59.691709
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I6EB4C046/5E15: '3406'
  IA690F999/FC95: '3406'
